### ISSUE TITLE
data.json の形式を教えてください

### ISSUE THREAD

**Issue by pdc-kaminaga** [kumon/DeepLearningExercise#1]
こんにちは。　
貴重なソースコードの提供ありがとうございます。
data.json の形式を教えていただけないでしょうか。

deep_features.py　でモデル作成を終え、
deep_features_faiss.py　を試みているのですが、

>データ
>jsonで保存してるのがナンセンスであることを理解しつつもjson。
>ちなみに、1 行 1 jsonのjsonl (json lines)となっている。

こういうことかな。。。
{"img": "/9j/4AAQSkZJRgABAQEAYABgAAD/4QA6RXhpZgAA・・・・・・｝
{"img": "/9j/4AAQSkZJRgABAQEBLAEsAAD/4iH8SUNDX1BS・・・・・・｝
{"img": "/9j/4AAQSkZJRgABAQEAtAC0AAD/2wBDAAICAgIC・・・・・・｝
・
・
のファイルを用意したのですが、以下のエラー出力を解決できずにいます。

Traceback (most recent call last):
  File "deep_features_faiss.py", line 84, in <module>
    main()
  File "deep_features_faiss.py", line 8, in main
    xb = np.array([np.array(json.loads(l.strip())).astype('float32') for l in f])
TypeError: float() argument must be a string or a number

**Comment by kumon** [comment]
こんにちは。4年前のことなので何も覚えていないのですが、コードから推測すると、

```
$ cat data.json
[1,2,3,4,5]
[6,7,8,9,10]
```
で、確認してみると、
```
>>> import numpy as np
>>> import json
>>> with open('data.json', 'r') as f:
...     xb = np.array([np.array(json.loads(l.strip())).astype('float32') for l in f])
...
>>> xb
array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]], dtype=float32)
```
ロードできています

**Comment by pdc-kaminaga** [comment]
回答ありがとうございます。
data.json に何のデータを格納するのか理解できていませんでした。
